### ISSUE TITLE
roadmap for provider

### ISSUE THREAD

**Issue by fenio** [Mirantis/terraform-provider-k0sctl#9]
I know that this provider is in early stage but I'm wondering how many efforts is going to devoted to make it solid replacement for running k0sctl. Is there any roadmap for it?

PR https://github.com/Mirantis/terraform-provider-k0sctl/pull/8 make that provider much more functional but I'm still wondering if you're planning to be equivalent of let's say the following k0sctl config file:

```yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: armada
spec:
  hosts:
  - ssh:
      address: 172.something
      user: root
      keyPath: ~/.ssh/id_rsa
      port: 22
    hostname: vm-0
    privateInterface: eth0:1
    role: controller
    installFlags:
    - --disable-components=metrics-server
    - --enable-metrics-scraper
  - ssh:
      address: 172.something
      user: root
      keyPath: ~/.ssh/id_rsa
      port: 22
    hostname: vm-1
    privateInterface: eth0:1
    role: worker
  - ssh:
      address: 172.something
      user: root
      keyPath: ~/.ssh/id_rsa
      port: 22
    hostname: vm-2
    privateInterface: eth0:1
    role: worker
  - ssh:
      address: 172.something
      user: root
      keyPath: ~/.ssh/id_rsa
      port: 22
    hostname: vm-3
    privateInterface: eth0:1
    role: worker
  k0s:
    version: 1.28.5+k0s.0
    dynamicConfig: false
    config:
      spec:
        network:
          provider: custom
          kubeProxy:
            disabled: true
        extensions:
          helm:
            repositories:
            - name: cilium
              url: https://helm.cilium.io
            charts:
            - name: cilium
              chartname: cilium/cilium
              version: "1.14.5"
              namespace: kube-system
              values: |2
                kubeProxyReplacement: true
                k8sServiceHost: 192.168.157.63
                k8sServicePort: 6443
                encryption:
                  enabled: true
                  type: wireguard
                  nodeEncryption: true
                operator:
                  replicas: 1
                  prometheus:
                    enabled: true
                bpf:
                  masquerade: true
                prometheus:
                  enabled: true
```
